version: '3.8'

services:
  fastbite:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: production
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    env_file:
      - .env.local
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3000/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      # Coolify/Traefik labels for automatic reverse proxy
      - "traefik.enable=true"
      - "traefik.http.routers.fastbite.rule=Host(`${DOMAIN:-localhost}`)"
      - "traefik.http.routers.fastbite.entrypoints=websecure"
      - "traefik.http.routers.fastbite.tls=true"
      - "traefik.http.routers.fastbite.tls.certresolver=letsencrypt"
      - "traefik.http.services.fastbite.loadbalancer.server.port=3000"
      # Caddy labels (alternative to Traefik)
      - "caddy=fastbite.${DOMAIN:-localhost}"
      - "caddy.reverse_proxy={{upstreams 3000}}"
    networks:
      - fastbite-network

networks:
  fastbite-network:
    driver: bridge